name: Auto upate named.root
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    name: Update named.cache
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Update the named.cache
        run: curl "https://www.internic.net/domain/named.root" -o "assets/named.root"
      - name: Push the named.root to github
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/named.cache
          git commit -m "Updated named.cache $(date)"
          git push
